services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/app/videos
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    # command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
