services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/app/videos
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
